dist: xenial
os: linux

language: shell

notifications:
  email: false

services:
  - postgresql

addons:
  postgresql: '9.6'
  apt:
   packages:
     - postgresql-9.6
     - postgresql-client-9.6
     - net-tools
     - libpcre3-dev
     - build-essential
     - lua5.1

env:
  global:
    # - SERF=0.7.0
    - LUAROCKS=3.2.1
    - KONG_VERSION=1.4.0
    - OPENSSL=1.1.1d
    - CASSANDRA=2.2.7
    - OPENRESTY=1.15.8.2
    - $CACHE_DIR=$HOME/cache
    - CQLSH_NO_BUNDLED=TRUE
    - LUA=5.1
  jobs:
    - TEST_SUITE=lint
    - TEST_SUITE=unit
    - TEST_SUITE=integration
    # - TEST_SUITE=plugins

before_install:
  - source .ci/setup_env.sh

install:
  - make install

script:
  - source .ci/run_tests.sh

cache:
  apt: true
  pip: true
  directories:
    - $CACHE_DIR
    - $HOME/.ccm/repository
