dist: xenial
os: linux

language: shell

notifications:
  email: false

services:
  - postgresql
  - cassandra

addons:
  postgresql: '9.6'
  apt:
   packages:
     - postgresql-9.6
     - postgresql-client-9.6
     - cassandra
     - net-tools
     - libpcre3-dev
     - build-essential

env:
  global:
    # - SERF=0.7.0
    - LUAROCKS=2.3.0
    - KONG_VERSION=1.3.0
    - OPENSSL=1.0.2h
    - CASSANDRA=2.2.7
    - OPENRESTY=1.9.15.1
    - $CACHE_DIR=$HOME/cache
    - PGPORT=5433
  jobs:
    - TEST_SUITE=lint
    - TEST_SUITE=unit
    - TEST_SUITE=integration
    # - TEST_SUITE=plugins

before_install:
  - source .ci/setup_env.sh

install:
  - make install
  
before_script:
  - printenv
  - psql -p $PGPORT -U postgres -c "create extension postgis"

script:
  - .ci/run_tests.sh

cache:
  apt: true
  pip: true
  directories:
    - $CACHE_DIR
    - $HOME/.ccm/repository
